- name: Pull latest postgresql image
  containers.podman.podman_image:
    name: registry.hub.docker.com/library/postgres:latest

- name: Start postgresql container
  containers.podman.podman_container:
    name: postgres
    image: registry.hub.docker.com/library/postgres:latest
    env:
      POSTGRES_PASSWORD: "{{ VAR_POSTGRESQL_PASSWORD }}"
    state: started
    volumes:
      - "{{ VAR_POSTGRESQL_DIR }}:/var/lib/postgresql/:Z"
    expose: 5432/tcp
    pod: db